name: python-ml
channels:
  - conda-forge
dependencies:
  - python=3.9.17
  - pip
  - pip:
    - mlflow==2.1.1
    - pathlib==1.0.1
    - lz4==3.1.3 
    - psutil==5.9.0 
    - typing-extensions==4.3.0 
    - cloudpickle==2.2.1
    - boto3==1.26.125
    - scikit-learn==1.3.1
